// Generated by BUCKLESCRIPT VERSION 1.7.4, PLEASE EDIT WITH CARE
'use strict';

import * as List          from "bs-platform/lib/es6/list.js";
import * as FromPlainText from "./fromPlainText.js";

function create(positions) {
  var positionedCell = function (position) {
    return /* tuple */[
            position,
            /* Alive */0
          ];
  };
  return List.map(positionedCell, positions);
}

var blinker = create(/* :: */[
      /* tuple */[
        1,
        1
      ],
      /* :: */[
        /* tuple */[
          2,
          1
        ],
        /* :: */[
          /* tuple */[
            3,
            1
          ],
          /* [] */0
        ]
      ]
    ]);

var spaceShip = create(/* :: */[
      /* tuple */[
        2,
        0
      ],
      /* :: */[
        /* tuple */[
          0,
          1
        ],
        /* :: */[
          /* tuple */[
            2,
            1
          ],
          /* :: */[
            /* tuple */[
              1,
              2
            ],
            /* :: */[
              /* tuple */[
                2,
                2
              ],
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var pulsar = create(/* :: */[
      /* tuple */[
        4,
        2
      ],
      /* :: */[
        /* tuple */[
          5,
          2
        ],
        /* :: */[
          /* tuple */[
            6,
            2
          ],
          /* :: */[
            /* tuple */[
              10,
              2
            ],
            /* :: */[
              /* tuple */[
                11,
                2
              ],
              /* :: */[
                /* tuple */[
                  12,
                  2
                ],
                /* :: */[
                  /* tuple */[
                    2,
                    4
                  ],
                  /* :: */[
                    /* tuple */[
                      7,
                      4
                    ],
                    /* :: */[
                      /* tuple */[
                        9,
                        4
                      ],
                      /* :: */[
                        /* tuple */[
                          14,
                          4
                        ],
                        /* :: */[
                          /* tuple */[
                            2,
                            5
                          ],
                          /* :: */[
                            /* tuple */[
                              7,
                              5
                            ],
                            /* :: */[
                              /* tuple */[
                                9,
                                5
                              ],
                              /* :: */[
                                /* tuple */[
                                  14,
                                  5
                                ],
                                /* :: */[
                                  /* tuple */[
                                    2,
                                    6
                                  ],
                                  /* :: */[
                                    /* tuple */[
                                      7,
                                      6
                                    ],
                                    /* :: */[
                                      /* tuple */[
                                        9,
                                        6
                                      ],
                                      /* :: */[
                                        /* tuple */[
                                          14,
                                          6
                                        ],
                                        /* :: */[
                                          /* tuple */[
                                            4,
                                            7
                                          ],
                                          /* :: */[
                                            /* tuple */[
                                              5,
                                              7
                                            ],
                                            /* :: */[
                                              /* tuple */[
                                                6,
                                                7
                                              ],
                                              /* :: */[
                                                /* tuple */[
                                                  10,
                                                  7
                                                ],
                                                /* :: */[
                                                  /* tuple */[
                                                    11,
                                                    7
                                                  ],
                                                  /* :: */[
                                                    /* tuple */[
                                                      12,
                                                      7
                                                    ],
                                                    /* :: */[
                                                      /* tuple */[
                                                        4,
                                                        9
                                                      ],
                                                      /* :: */[
                                                        /* tuple */[
                                                          5,
                                                          9
                                                        ],
                                                        /* :: */[
                                                          /* tuple */[
                                                            6,
                                                            9
                                                          ],
                                                          /* :: */[
                                                            /* tuple */[
                                                              10,
                                                              9
                                                            ],
                                                            /* :: */[
                                                              /* tuple */[
                                                                11,
                                                                9
                                                              ],
                                                              /* :: */[
                                                                /* tuple */[
                                                                  12,
                                                                  9
                                                                ],
                                                                /* :: */[
                                                                  /* tuple */[
                                                                    2,
                                                                    10
                                                                  ],
                                                                  /* :: */[
                                                                    /* tuple */[
                                                                      7,
                                                                      10
                                                                    ],
                                                                    /* :: */[
                                                                      /* tuple */[
                                                                        9,
                                                                        10
                                                                      ],
                                                                      /* :: */[
                                                                        /* tuple */[
                                                                          14,
                                                                          10
                                                                        ],
                                                                        /* :: */[
                                                                          /* tuple */[
                                                                            2,
                                                                            11
                                                                          ],
                                                                          /* :: */[
                                                                            /* tuple */[
                                                                              7,
                                                                              11
                                                                            ],
                                                                            /* :: */[
                                                                              /* tuple */[
                                                                                9,
                                                                                11
                                                                              ],
                                                                              /* :: */[
                                                                                /* tuple */[
                                                                                  14,
                                                                                  11
                                                                                ],
                                                                                /* :: */[
                                                                                  /* tuple */[
                                                                                    2,
                                                                                    12
                                                                                  ],
                                                                                  /* :: */[
                                                                                    /* tuple */[
                                                                                      7,
                                                                                      12
                                                                                    ],
                                                                                    /* :: */[
                                                                                      /* tuple */[
                                                                                        9,
                                                                                        12
                                                                                      ],
                                                                                      /* :: */[
                                                                                        /* tuple */[
                                                                                          14,
                                                                                          12
                                                                                        ],
                                                                                        /* :: */[
                                                                                          /* tuple */[
                                                                                            4,
                                                                                            14
                                                                                          ],
                                                                                          /* :: */[
                                                                                            /* tuple */[
                                                                                              5,
                                                                                              14
                                                                                            ],
                                                                                            /* :: */[
                                                                                              /* tuple */[
                                                                                                6,
                                                                                                14
                                                                                              ],
                                                                                              /* :: */[
                                                                                                /* tuple */[
                                                                                                  10,
                                                                                                  14
                                                                                                ],
                                                                                                /* :: */[
                                                                                                  /* tuple */[
                                                                                                    11,
                                                                                                    14
                                                                                                  ],
                                                                                                  /* :: */[
                                                                                                    /* tuple */[
                                                                                                      12,
                                                                                                      14
                                                                                                    ],
                                                                                                    /* [] */0
                                                                                                  ]
                                                                                                ]
                                                                                              ]
                                                                                            ]
                                                                                          ]
                                                                                        ]
                                                                                      ]
                                                                                    ]
                                                                                  ]
                                                                                ]
                                                                              ]
                                                                            ]
                                                                          ]
                                                                        ]
                                                                      ]
                                                                    ]
                                                                  ]
                                                                ]
                                                              ]
                                                            ]
                                                          ]
                                                        ]
                                                      ]
                                                    ]
                                                  ]
                                                ]
                                              ]
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var glider = FromPlainText.toUniverse("\n........................O...........\n......................O.O...........\n............OO......OO............OO\n...........O...O....OO............OO\nOO........O.....O...OO..............\nOO........O...O.OO....O.O...........\n..........O.....O.......O...........\n...........O...O....................\n............OO......................\n");

var bakersDozen = FromPlainText.toUniverse("\nOO.........OO\nOOOO.O.....OO\nO.O..OOO\n...........O\n....OO....O.O\n....O.....O..O....O\n...........OO....OO\n\n...............OOO..O.O\n..........OO.....O.OOOO\n..........OO.........OO\n");

var thunderbird = FromPlainText.toUniverse("\nOOO\n\n.O\n.O\n.O\n");

var all_000 = /* tuple */[
  "blinker",
  blinker
];

var all_001 = /* :: */[
  /* tuple */[
    "spaceShip",
    spaceShip
  ],
  /* :: */[
    /* tuple */[
      "pulsar",
      pulsar
    ],
    /* :: */[
      /* tuple */[
        "glider",
        glider
      ],
      /* :: */[
        /* tuple */[
          "bakersDozen",
          bakersDozen
        ],
        /* :: */[
          /* tuple */[
            "thunderbird",
            thunderbird
          ],
          /* [] */0
        ]
      ]
    ]
  ]
];

var all = /* :: */[
  all_000,
  all_001
];

export {
  create      ,
  blinker     ,
  spaceShip   ,
  pulsar      ,
  glider      ,
  bakersDozen ,
  thunderbird ,
  all         ,
  
}
/* blinker Not a pure module */
