// Generated by BUCKLESCRIPT VERSION 1.7.4, PLEASE EDIT WITH CARE
'use strict';

import * as Pervasives from "bs-platform/lib/es6/pervasives.js";

function head(param) {
  if (param) {
    return /* Some */[param[0]];
  } else {
    return /* None */0;
  }
}

function range(from, until) {
  var _l = /* [] */0;
  var _a = from;
  var b = until;
  while(true) {
    var a = _a;
    var l = _l;
    if (a === b) {
      return Pervasives.$at(l, /* :: */[
                  b,
                  /* [] */0
                ]);
    } else {
      _a = a + 1 | 0;
      _l = Pervasives.$at(l, /* :: */[
            a,
            /* [] */0
          ]);
      continue ;
      
    }
  };
}

export {
  head  ,
  range ,
  
}
/* No side effect */
