// Generated by BUCKLESCRIPT VERSION 1.7.4, PLEASE EDIT WITH CARE
'use strict';

import * as Pixi       from "./pixi.js";
import * as Block      from "bs-platform/lib/es6/block.js";
import * as Curry      from "bs-platform/lib/es6/curry.js";
import * as Start      from "./start.js";
import * as Types      from "./types.js";
import * as Option     from "./option.js";
import * as Tea_app    from "bucklescript-tea/lib/es6/src/tea_app.js";
import * as Tea_cmd    from "bucklescript-tea/lib/es6/src/tea_cmd.js";
import * as Tea_sub    from "bucklescript-tea/lib/es6/src/tea_sub.js";
import * as Examples   from "./examples.js";
import * as Tea_html   from "bucklescript-tea/lib/es6/src/tea_html.js";
import * as Tea_time   from "bucklescript-tea/lib/es6/src/tea_time.js";
import * as Pervasives from "bs-platform/lib/es6/pervasives.js";

function drawCircle(graphics, x, y, r) {
  graphics.lineStyle(0);
  graphics.beginFill(16776971, 0.5);
  graphics.drawCircle(x, y, r);
  return graphics.endFill();
}

function startAnimation(graphics, renderer, stage) {
  var animate = function (t, _) {
    var x = 200 * Math.sin(t) + 300;
    var y = 200 * Math.cos(t) + 300;
    graphics.clear();
    drawCircle(graphics, x, y, 60);
    renderer.render(stage);
    var partial_arg = t + 0.05;
    requestAnimationFrame(function (param) {
          return animate(partial_arg, param);
        });
    return /* () */0;
  };
  requestAnimationFrame(function (param) {
        return animate(0.0, param);
      });
  return /* () */0;
}

function putSprite(stage, position, param) {
  if (param) {
    var s = param[0];
    Curry._2(Pixi.Container[/* addChild */0], stage, /* Sprite */Block.__(1, [s]));
    Curry._2(Pixi.Sprite[/* updatePosition */0], s, position);
    return /* () */0;
  } else {
    console.log("No valid sprite loaded");
    return /* () */0;
  }
}

function setup() {
  var opts = {
    antialias: /* true */1,
    transparent: /* false */0
  };
  var renderer = PIXI.autoDetectRenderer(800, 600, opts);
  var stage = Curry._1(Pixi.Container[/* create */1], /* () */0);
  var graphics = new PIXI.Graphics();
  var s = renderer.view.style;
  var maybePack = Curry._1(Pixi.Resources[/* create */0], "space/space.json");
  var maybeBackground = Option.map(function (prim) {
        return new PIXI.Sprite(prim);
      }, Option.andThen(Curry._1(Pixi.Resources[/* texture */1], "background.png"), maybePack));
  var maybeShip = Option.map(function (prim) {
        return new PIXI.Sprite(prim);
      }, Option.andThen(Curry._1(Pixi.Resources[/* texture */1], "spaceship.png"), maybePack));
  s.setProperty("border", "1px blue solid");
  renderer.view.style.border = "5px red solid";
  document.body.appendChild(renderer.view);
  Curry._2(Pixi.Container[/* addChild */0], stage, /* Graphics */Block.__(0, [graphics]));
  drawCircle(graphics, 300, 300, 60);
  startAnimation(graphics, renderer, stage);
  putSprite(stage, /* tuple */[
        0,
        0
      ], maybeBackground);
  putSprite(stage, /* tuple */[
        200,
        100
      ], maybeShip);
  return renderer.render(stage);
}

function myMain() {
  return Curry._2(Pixi.Loader[/* load */3], setup, Curry._2(Pixi.Loader[/* onProgress */2], function (p) {
                  console.log(Pervasives.string_of_float(p));
                  return /* () */0;
                }, Curry._2(Pixi.Loader[/* add */1], /* array */["space/space.json"], Pixi.Loader[/* init */0])));
}

function init(universe) {
  return /* record */[
          /* universe */universe,
          /* examples */Examples.all,
          /* viewPort */Types.newViewPort(0, 0, 20, 20, 35),
          /* running : true */1
        ];
}

function subscriptions(model) {
  if (model[/* running */3]) {
    return Tea_time.every(200 * Tea_time.millisecond, function () {
                return /* Evolve */1;
              });
  } else {
    return Tea_sub.none;
  }
}

function view(model) {
  return Tea_html.div(/* None */0, /* None */0, /* [] */0, /* :: */[
              Tea_html.text(Pervasives.string_of_bool(model[/* running */3])),
              /* [] */0
            ]);
}

function partial_arg_000() {
  return /* tuple */[
          init(Examples.glider),
          Tea_cmd.none
        ];
}

var partial_arg = /* record */[
  partial_arg_000,
  /* update */Start.update,
  /* view */view,
  /* subscriptions */subscriptions
];

function main(param, param$1) {
  return Tea_app.standardProgram(partial_arg, param, param$1);
}

export {
  drawCircle     ,
  startAnimation ,
  putSprite      ,
  setup          ,
  myMain         ,
  init           ,
  subscriptions  ,
  view           ,
  main           ,
  
}
/* Pixi Not a pure module */
