// Generated by BUCKLESCRIPT VERSION 1.7.4, PLEASE EDIT WITH CARE
'use strict';

import * as Tea_app    from "bucklescript-tea/lib/es6/src/tea_app.js";
import * as Tea_cmd    from "bucklescript-tea/lib/es6/src/tea_cmd.js";
import * as Tea_sub    from "bucklescript-tea/lib/es6/src/tea_sub.js";
import * as Tea_html   from "bucklescript-tea/lib/es6/src/tea_html.js";
import * as Pervasives from "bs-platform/lib/es6/pervasives.js";

var Graphics = /* module */[];

var Container = /* module */[];

var Renderer = /* module */[];

function drawCircle(graphics, x, y, r) {
  graphics.lineStyle(0);
  graphics.beginFill(16776971, 0.5);
  graphics.drawCircle(x, y, r);
  return graphics.endFill();
}

function startAnimation(graphics, renderer, stage) {
  var animate = function (t, _) {
    var x = 200 * Math.sin(t) + 300;
    var y = 200 * Math.cos(t) + 300;
    graphics.clear();
    drawCircle(graphics, x, y, 60);
    renderer.render(stage);
    var partial_arg = t + 0.05;
    requestAnimationFrame(function (param) {
          return animate(partial_arg, param);
        });
    return /* () */0;
  };
  requestAnimationFrame(function (param) {
        return animate(0.0, param);
      });
  return /* () */0;
}

function foo() {
  var opts = {
    antialias: /* true */1,
    transparent: /* false */0
  };
  var renderer = PIXI.autoDetectRenderer(800, 600, opts);
  var stage = new PIXI.Container();
  var graphics = new PIXI.Graphics();
  document.body.appendChild(renderer.view);
  stage.addChild(graphics);
  drawCircle(graphics, 300, 300, 60);
  renderer.render(stage);
  return startAnimation(graphics, renderer, stage);
}

function init() {
  return /* tuple */[
          /* record */[/* notUsedYet */42],
          Tea_cmd.none
        ];
}

function update(model, _) {
  return /* tuple */[
          model,
          Tea_cmd.none
        ];
}

function subscriptions() {
  return Tea_sub.none;
}

function view(model) {
  return Tea_html.div(/* None */0, /* None */0, /* [] */0, /* :: */[
              Tea_html.text(Pervasives.string_of_int(model[/* notUsedYet */0])),
              /* [] */0
            ]);
}

var partial_arg = /* record */[
  /* init */init,
  /* update */update,
  /* view */view,
  /* subscriptions */subscriptions
];

function main(param, param$1) {
  return Tea_app.standardProgram(partial_arg, param, param$1);
}

var nothingYet = /* NothingYet */0;

var somethingElse = /* SomethingElse */1;

export {
  Graphics       ,
  Container      ,
  Renderer       ,
  drawCircle     ,
  startAnimation ,
  foo            ,
  nothingYet     ,
  somethingElse  ,
  init           ,
  update         ,
  subscriptions  ,
  view           ,
  main           ,
  
}
/* No side effect */
