// Generated by BUCKLESCRIPT VERSION 1.7.4, PLEASE EDIT WITH CARE
'use strict';

import * as Pixi       from "./pixi.js";
import * as Block      from "bs-platform/lib/es6/block.js";
import * as Curry      from "bs-platform/lib/es6/curry.js";
import * as Option     from "./option.js";
import * as Pervasives from "bs-platform/lib/es6/pervasives.js";

function putSprite(stage, position, param) {
  if (param) {
    var s = param[0];
    Curry._2(Pixi.Container[/* addChild */0], stage, /* Sprite */Block.__(1, [s]));
    Curry._2(Pixi.Sprite[/* updatePosition */0], s, position);
    return /* () */0;
  } else {
    console.log("No valid sprite loaded");
    return /* () */0;
  }
}

var model = /* record */[
  /* renderer : None */0,
  /* stage : None */0,
  /* maybeShip : None */0
];

Curry._2(Pixi.Loader[/* load */3], function (param) {
      var t = model;
      var opts = {
        antialias: /* true */1,
        transparent: /* false */0
      };
      var renderer = PIXI.autoDetectRenderer(800, 600, opts);
      var stage = Curry._1(Pixi.Container[/* create */1], /* () */0);
      var maybePack = Curry._1(Pixi.Resources[/* create */0], "space/space.json");
      var maybeBackground = Option.map(function (prim) {
            return new PIXI.Sprite(prim);
          }, Option.andThen(Curry._1(Pixi.Resources[/* texture */1], "background.png"), maybePack));
      var maybeShip = Option.map(function (prim) {
            return new PIXI.Sprite(prim);
          }, Option.andThen(Curry._1(Pixi.Resources[/* texture */1], "spaceship.png"), maybePack));
      document.body.appendChild(renderer.view);
      putSprite(stage, /* tuple */[
            0,
            0
          ], maybeBackground);
      renderer.render(stage);
      t[/* renderer */0] = /* Some */[renderer];
      t[/* stage */1] = /* Some */[stage];
      t[/* maybeShip */2] = maybeShip;
      return /* () */0;
    }, Curry._2(Pixi.Loader[/* onProgress */2], function (p) {
          console.log(Pervasives.string_of_float(p));
          return /* () */0;
        }, Curry._2(Pixi.Loader[/* add */1], /* array */["space/space.json"], Pixi.Loader[/* init */0])));

function render(_, _$1) {
  console.log("rendering");
  return /* () */0;
}

var init = model;

export {
  init   ,
  render ,
  
}
/*  Not a pure module */
