// Generated by BUCKLESCRIPT VERSION 1.7.4, PLEASE EDIT WITH CARE
'use strict';

import * as Curry from "bs-platform/lib/es6/curry.js";

function map(f, a) {
  if (a) {
    return /* Some */[Curry._1(f, a[0])];
  } else {
    return /* None */0;
  }
}

function andThen(f, a) {
  if (a) {
    return Curry._1(f, a[0]);
  } else {
    return /* None */0;
  }
}

function withDefault($$default, opt) {
  if (opt) {
    return opt[0];
  } else {
    return $$default;
  }
}

export {
  map         ,
  andThen     ,
  withDefault ,
  
}
/* No side effect */
