// Generated by BUCKLESCRIPT VERSION 1.7.4, PLEASE EDIT WITH CARE
'use strict';

import * as Js_primitive from "bs-platform/lib/es6/js_primitive.js";

function updatePosition(sprite, param) {
  sprite.position.set(param[0], param[1]);
  return sprite;
}

var Sprite = /* module */[/* updatePosition */updatePosition];

var Graphics = /* module */[];

function addChild(container, child) {
  container.addChild(child[0]);
  return /* () */0;
}

function Container_001() {
  return new PIXI.Container();
}

var Container = /* module */[
  /* addChild */addChild,
  Container_001
];

var Renderer = /* module */[];

var LoaderProcess = /* module */[];

function textures(name, loader) {
  return Js_primitive.null_undefined_to_opt(loader.textures[name]);
}

var Loader = /* module */[
  /* LoaderProcess */LoaderProcess,
  /* textures */textures
];

export {
  Sprite    ,
  Graphics  ,
  Container ,
  Renderer  ,
  Loader    ,
  
}
/* No side effect */
