// Generated by BUCKLESCRIPT VERSION 1.7.4, PLEASE EDIT WITH CARE
'use strict';


function updatePosition(sprite, param) {
  sprite.x = param[0];
  sprite.y = param[1];
  return sprite;
}

var Sprite = /* module */[/* updatePosition */updatePosition];

var Graphics = /* module */[];

function addChild(container, child) {
  container.addChild(child[0]);
  return /* () */0;
}

function Container_001() {
  return new PIXI.Container();
}

var Container = /* module */[
  /* addChild */addChild,
  Container_001
];

var Renderer = /* module */[];

var LoaderProcess = /* module */[];

var Loader = /* module */[/* LoaderProcess */LoaderProcess];

export {
  Sprite    ,
  Graphics  ,
  Container ,
  Renderer  ,
  Loader    ,
  
}
/* No side effect */
