// Generated by BUCKLESCRIPT VERSION 1.7.4, PLEASE EDIT WITH CARE
'use strict';


function newViewPort(a, b, c, d, e) {
  return /* record */[
          /* xMin */a,
          /* yMin */b,
          /* xMax */c,
          /* yMax */d,
          /* cellSize */e
        ];
}

export {
  newViewPort ,
  
}
/* No side effect */
