// Generated by BUCKLESCRIPT VERSION 1.7.4, PLEASE EDIT WITH CARE
'use strict';

import * as Tea_html       from "bucklescript-tea/lib/es6/src/tea_html.js";
import * as MyPixiRenderer from "./myPixiRenderer.js";

function view(model) {
  MyPixiRenderer.render(model[/* pixi */4], model[/* viewPort */2][/* cellSize */4], model[/* universe */0]);
  return Tea_html.div(/* None */0, /* None */0, /* [] */0, /* [] */0);
}

export {
  view ,
  
}
/* MyPixiRenderer Not a pure module */
